### ISSUE TITLE
-t queues output misses nukleus info

### ISSUE THREAD

**Issue by jitsni** [reaktivity/command-log.java#14]
$ java -Dreaktor.streams.buffer.capacity=0x800000 -jar ~/src/command-log.java/target/command-log-develop-SNAPSHOT.jar -d . -t queues | grep 'http#tls.streams'

 http#tls.streams 0
 http#tls.streams 3
 http#tls.streams 2

There are three corresponding files but cannot relate to the above output since it doesn't contain nukleus info
./http-inject/streams/http#tls
./tls/streams/http#tls
./ws/streams/http#tls

**Comment by jfallows** [comment]
Streams buffers are now per core, no longer per nukleus, and each queue name indicates the corresponding core.
```
{"name":"data0", "head":0, "tail":0, "depth":0}
{"name":"data63", "head":784, "tail":784, "depth":0}
```
